---
default_desc: The comprehensive Raspberry Pi GPIO Pinout guide for the original Raspberry
  Pi, B+ and Pi 2
default_title: Raspberry Pi GPIO Pinout - Pi 1, B+, Pi 2
title_suffix: " at Raspberry Pi GPIO Pinout"
base_url: /pinout/
resource_url: /resources/
domain: pinout.xyz
url_suffix:
urls:
  GND: ground
strings:
- made_by: '* Made by {manufacturer}'
- type_hat: '* HAT form-factor'
- type_phat: 'pHAT/non-HAT (no EEPROM)'
- type_classic: '* Classic form-factor'
- pin_header: '* {} pin header'
- uses_i2c: '* Uses I2C'
- wiring_pi_pin: 'Wiring Pi pin {}'
overlays:
- ground
- uart
- i2c
- spi
- arduino-spi
- wiringpi
- iqaudio-pi-dac
- display-o-tron
- display-o-tron-hat
- dots
- explorer-hat
- explorer-hat-pro
- piano-hat
- piborg-ledborg
- pibrella
- piglow
- rtk-000-001
- sense-hat
- skywriter-hat
- traffic-hat
- unicorn-hat
