---
default_desc: Raspberry Pi, B+ ve Pi 2 için Pin şematiği
default_title: Raspberry Pi GPIO Pinleri - Pi 1, B+, Pi 2
title_suffix: " - Raspberry Pi Pinleri"
base_url: /pinout/
resource_url: /resources/
domain: tr.pinout.xyz
url_suffix: ''
urls:
  GND: ground_toprak
strings:
- made_by: 'Made by {manufacturer}'
- type_hat: 'HAT form-factor'
- type_classic: 'Classic form-factor'
- pin_header: '{} pin header'
- uses_i2c: 'Uses I2C'
- wiring_pi_pin: 'Wiring Pi pin {}'
overlays:
- ground
- spi
- uart
- i2c
- wiringpi
- arduino-spi
- rtk-000-001
- piborg-ledborg
- piglow
- pibrella
- unicorn-hat
- skywriter-hat
- explorer-hat-pro
- explorer-hat
- display-o-tron
- dots