---
default_desc: Pinout le guide complet des broches GPIO de la Raspberry Pi
default_title: Raspberry Pi GPIO pour Pi 1, B+, Pi 2
title_suffix: " Raspberry Pi GPIO Pinout"
urls:
  GND: masse
overlays:
- masse
- spi
- uart
- i2c
- wiringpi
- arduino-spi
- rtk-000-001
- piborg-ledborg
- piglow
- pibrella
- unicorn-hat
- skywriter-hat
- explorer-hat-pro
- explorer-hat
- display-o-tron
- dots
- traffic-hat
