---
default_desc: Le guide complet des broches GPIO de la Raspberry Pi
  Pi, B+ and Pi 2
default_title: Raspberry Pi GPIO Pinout - Pi 1, B+, Pi 2
title_suffix: " Raspberry Pi GPIO Pinout"
base_url: /pinout/
resource_url: /resources/
domain: fr.pinout.xyz
url_suffix:
urls:
  GND: masse
strings:
- details: 'Détails'
- made_by: 'produit {manufacturer}'
- type_hat: 'format HAT'
- type_phat: 'format pHAT'
- type_classic: 'format Classic'
- pin_header: '{} broches'
- uses_eeprom: 'EEPROM'
- uses_i2c: 'bus I2C'
- uses_spi: 'bus SPI'
- uses_5v_and_3v3: 'Alim. 5v et 3v3'
- uses_5v: 'Alim. 5v'
- uses_3v3: 'Alim. 3v3'
- wiring_pi_pin: 'broche Wiring Pi {}'
- uses_n_gpio_pins: '{} broches GPIO actives'
- bcm_pin_rev1_pi: 'broche BCM {} sur Raspi Rev 1'
- physical_pin_n: 'broche physique {}'
- more_information: 'plus d''info'
- github_repository: 'lien GitHub'
- buy_now: 'achat'
- details: 'Détails'
featured:
- display-o-tron
- piborg-ledborg
- pibrella
- rtk-000-001
overlays:
- ground
- i2c
- spi
- uart
- wiringpi
- 4tronix-picon-zero
- ab-1-wire-plus
- ab-rtc-pi-zero
- iqaudio-pi-dac
- display-o-tron
- display-o-tron-hat
- rpf-dots
- explorer-hat
- explorer-hat-pro
- piano-hat
- piborg-ledborg
- pibrella
- piglow
- rtk-000-001
- skywriter-hat
- traffic-hat
- unicorn-hat
