---
default_desc: The comprehensive Add-on boards & GPIO Pinout guide for the Raspberry Pi
default_title: Raspberry Pi GPIO Pinout
title_suffix: " at Raspberry Pi GPIO Pinout"
base_url: /pinout/
resource_url: /resources/
domain: pinout.xyz
url_suffix:
urls:
  GND: ground
strings:
- made_by: 'Made by {manufacturer}'
- type_hat: 'HAT form-factor'
- type_phat: 'pHAT form-factor'
- type_classic: 'Classic form-factor'
- pin_header: '{} pin header'
- uses_i2c: 'Uses I2C'
- uses_spi: 'Uses SPI'
- wiring_pi_pin: 'Wiring Pi pin {}'
- uses_n_gpio_pins: 'Uses {} GPIO pins'
- bcm_pin_rev1_pi: 'BCM pin {} on Rev 1 ( very early ) Pi'
- physical_pin_n: 'Physical pin {}'
- more_information: 'More Information'
- github_repository: 'GitHub Repository'
- buy_now: 'Buy Now'
featured:
- explorer-phat
- enviro-phat
- ab-adc-pi-zero
- redbear-iot-hat
overlays:
- ground
- uart
- i2c
- spi
- arduino-spi
- wiringpi
- ab-1-wire-plus
- ab-adc-differential-pi
- ab-adc-pi-plus
- ab-adc-pi-zero
- ab-io-pi-plus
- ab-rtc-pi-plus
- ab-serial-pi-plus
- adafruit-cap-mpr121
- cirruslogic-audio-card
- display-o-tron
- display-o-tron-hat
- discohat
- drum-hat
- espiot-phat
- explorer-hat
- explorer-hat-pro
- explorer-phat
- blinkt
- enviro-phat
- iface-gpclk
- iface-dpi
- iface-pcm
- iface-sd
- iface-jtag
- phat-dac
- propeller-hat
- iqaudio-pi-dac
- iqaudio-pi-digiamp
- piano-hat
- piborg-ledborg
- pibrella
- piglow
- rpf-dots
- redbear-iot-hat
- rtk-000-001
- scroll-phat
- sense-hat
- skywriter-hat
- traffic-hat
- unicorn-hat
- unicorn-phat
- uugear-zero4u
- uugear-7port-usb-hub
- uugear-witty-pi
- analog-zero
- carberry
