---
default_desc: La guía detallada sobre el pinout del GPIO de Raspberry Pi para Raspberry
default_title: Pinout de Raspberry Pi - Pi 1, B+, Pi 2
title_suffix: " at Raspberry Pi GPIO Pinout"
base_url: /pinout/
resource_url: /resources/
domain: es.pinout.xyz
url_suffix:
urls:
  GND: tierra
strings:
- made_by: 'Hecho por {manufacturer}'
- type_hat: 'formato HAT'
- type_phat: 'formato pHAT'
- type_classic: 'formato clásico'
- pin_header: '{} pin header'
- uses_eeprom: 'Usa EEPROM'
- uses_i2c: 'Usa I2C'
- uses_spi: 'Usa SPI'
- uses_5v_and_3v3: 'Alimentación 5v+3v3'
- uses_5v: 'Alimentación 5v'
- uses_3v3: 'Alimentación 3v3'
- wiring_pi_pin: 'Wiring Pi pin {}'
- uses_n_gpio_pins: 'Usa {} GPIO pins'
- bcm_pin_rev1_pi: 'BCM pin {} on Rev 1 ( very early ) Pi'
- physical_pin_n: 'Physical pin {}'
- more_information: 'More Information'
- github_repository: 'GitHub Repository'
- buy_now: 'Buy Now'
- details: 'Details'
featured:
- ab-adc-pi-zero
- analog-zero
- piborg-ledborg
- pibrella
overlays:
- ground
- iface-dpi
- iface-gpclk
- iface-jtag
- iface-1wire
- iface-pcm
- iface-sd
- i2c
- spi
- uart
- wiringpi
- ab-1-wire-plus
- ab-adc-differential-pi
- ab-adc-pi-plus
- ab-adc-pi-zero
- ab-io-pi-plus
- ab-rtc-pi-plus
- ab-serial-pi-plus
- adafruit-cap-mpr121
- adafruit-servo-hat
- analog-zero
- blinkt
- carberry
- cirruslogic-audio-card
- discohat
- display-o-tron
- display-o-tron-hat
- drum-hat
- enviro-phat
- espiot-phat
- explorer-hat
- explorer-hat-pro
- explorer-phat
- iqaudio-pi-dac
- iqaudio-pi-digiamp
- microdot-phat
- phat-dac
- pi-liter
- piano-hat
- piborg-ledborg
- pibrella
- piglow
- propeller-hat
- rpf-dots
- rtk-000-001
- skywriter-hat
- traffic-hat
- unicorn-hat
